# Generated by Django 2.0.2 on 2018-02-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_level_three', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAdded',
            new_name='newuser',
        ),
    ]
